# Generated by Django 2.2.16 on 2020-10-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mel_site', '0002_sponsors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsors',
            name='videofile',
        ),
        migrations.AddField(
            model_name='sponsors',
            name='image',
            field=models.ImageField(default='null', upload_to='logos'),
        ),
    ]
