# Generated by Django 2.2.16 on 2020-10-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mel_site', '0003_auto_20201006_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='category',
            field=models.CharField(choices=[('LOGO', 'Logo'), ('IMAGE', 'Image')], default='IMAGE', max_length=5),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='image',
            field=models.ImageField(default='null', upload_to='pictures'),
        ),
    ]
