# Generated by Django 2.2.16 on 2020-10-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mel_site', '0004_auto_20201007_1912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponsors',
            new_name='Images',
        ),
    ]
