# Generated by Django 2.2.16 on 2020-10-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mel_site', '0005_auto_20201007_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='category',
            field=models.CharField(choices=[('LOGO1', 'Logo Tier 1'), ('LOGO2', 'Logo Tier 2'), ('LOGO3', 'Logo Tier 3'), ('IMAGE', 'Image')], default='IMAGE', max_length=5),
        ),
    ]
