  version: '3'
    
  services:
    # db:
    #   image: postgres
    #   environment:
    #     - POSTGRES_DB=postgres
    #     - POSTGRES_USER=postgres
    #     - POSTGRES_PASSWORD=postgres
    web:
      build: .
      
      #command: python manage.py runserver 0.0.0.0:8000
      container_name: mel_site
      volumes:
        - .:/code
      ports:
        - "8005:80"
      # depends_on:
      #   - db
      volumes: 
        #mount the working directory/elisa folder as www/html
       - $PWD/www:/var/www/html